export const BDSP_OBTAIN = {
  "11": "Evolve Caterpie",
  "7": "Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "19": "Route 225, 226, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "8": "Evolve Squirtle",
  "17": "Evolve Pidgey",
  "10": "Spacious Cave, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "13": "Trade/migrate from another game",
  "15": "Trade/migrate from another game",
  "2": "Evolve Bulbasaur",
  "5": "Evolve Charmander",
  "3": "Evolve Bulbasaur/Ivysaur",
  "18": "Evolve Pidgey/Pidgeotto",
  "16": "Route 229",
  "20": "Route 225, 226, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "4": "Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "21": "Route 225, 226",
  "12": "Evolve Caterpie/Metapod",
  "1": "Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "14": "Trade/migrate from another game",
  "6": "Evolve Charmander/Charmeleon",
  "28": "Trade/migrate from another game",
  "24": "Evolve Ekans",
  "25": "Trophy Garden",
  "23": "Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "33": "Route 221, Valor Lakefront, Grassland Cave, Swampy Cave, Dazzling Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Stargleam Cavern, Bogsunk Cavern",
  "31": "Evolve Nidoran♀/Nidorina",
  "36": "Evolve Clefairy/Cleffa",
  "29": "Route 201, Grassland Cave, Swampy Cave, Dazzling Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Stargleam Cavern, Bogsunk Cavern",
  "40": "Trade/migrate from another game",
  "37": "Trade/migrate from another game",
  "32": "Route 201, Grassland Cave, Swampy Cave, Dazzling Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Stargleam Cavern, Bogsunk Cavern",
  "34": "Evolve Nidoran♂/Nidorino",
  "26": "Evolve Pikachu/Pikachu (Partner Pikachu)/Pichu",
  "30": "Route 221, Valor Lakefront, Grassland Cave, Swampy Cave, Dazzling Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Stargleam Cavern, Bogsunk Cavern",
  "27": "Trade/migrate from another game",
  "41": "Route 203, 204, 206, 207, 208, 209, 211, 216, 217, Acuity Lakefront, Iron Island, Lost Tower, Mt. Coronet, Oreburgh Gate, Oreburgh Mine, Ravaged Path, Wayward Cave, Spacious Cave, Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "42": "Route 227, Iron Island, Lost Tower, Mt. Coronet, Oreburgh Gate, Ravaged Path, Snowpoint Temple, Stark Mountain, Turnback Cave, Victory Road, Spacious Cave, Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "46": "Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "43": "Route 229, 230, Spacious Cave, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "47": "Evolve Paras",
  "9": "Evolve Squirtle/Wartortle",
  "44": "Route 224, 229, 230, Spacious Cave, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "48": "Route 229, Spacious Cave, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "54": "Route 203, 204, 205, 208, 209, 210, 212, 214, Celestic Town, Eterna City, Great Marsh, Lake Acuity, Lake Valor, Lake Verity, Oreburgh Gate, Ravaged Path, Twinleaf Town, Spacious Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "49": "Route 229, Spacious Cave, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "45": "Evolve Oddish/Gloom",
  "51": "Route 228",
  "55": "Route 203, 204, 205, 208, 209, 210, 212, 214, 225, 226, 230, Celestic Town, Eterna City, Lake Acuity, Lake Valor, Lake Verity, Oreburgh Gate, Ravaged Path, Resort Area, Sendoff Spring, Twinleaf Town",
  "57": "Route 225, 226, Spacious Cave, Grassland Cave, Sunlit Cavern",
  "35": "Mt. Coronet",
  "53": "Trade/migrate from another game",
  "58": "Spacious Cave, Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "64": "Route 215, Victory Road, Dazzling Cave, Stargleam Cavern",
  "50": "Route 228",
  "61": "Route 225, 227, 228, Grassland Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "59": "Evolve Growlithe/Hisuian Growlithe",
  "66": "Route 207, 208, 210, Mt. Coronet, Spacious Cave, Grassland Cave, Whiteout Cave, Sunlit Cavern",
  "65": "Evolve Abra/Kadabra",
  "56": "Route 225, 226, Spacious Cave, Grassland Cave, Sunlit Cavern",
  "68": "Evolve Machop/Machoke",
  "52": "Trade/migrate from another game",
  "73": "Route 205, 213, 218, 219, 220, 221, 222, 223, 224, 226, 230, Canalave City, Fuego Ironworks, Iron Island, Pastoria City, Pokémon League, Sunyshore City, Valley Windworks, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "63": "Route 203, 215",
  "60": "Route 225, 227, 228, Grassland Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "74": "Route 206, 207, 210, 211, 214, 215, Iron Island, Mt. Coronet, Oreburgh Gate, Oreburgh Mine, Ravaged Path, Ruin Maniac Tunnel, Stark Mountain, Valor Lakefront, Wayward Cave, Spacious Cave, Rocky Cave, Volcanic Cave, Big Bluff Cavern, Typhlo Cavern",
  "67": "Route 210, 211, 216, 217, 225, 226, Acuity Lakefront, Mt. Coronet, Stark Mountain, Victory Road, Spacious Cave, Grassland Cave, Whiteout Cave, Sunlit Cavern",
  "71": "Evolve Bellsprout/Weepinbell",
  "69": "Route 229, 230, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "70": "Route 224, 229, 230, Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "72": "Route 205, 213, 218, 219, 220, 221, 222, Canalave City, Fuego Ironworks, Iron Island, Pastoria City, Valley Windworks, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "78": "Evolve Ponyta/Galarian Ponyta",
  "82": "Evolve Magnemite",
  "84": "Route 201, Spacious Cave, Grassland Cave, Sunlit Cavern",
  "80": "Trade/migrate from another game",
  "81": "Fuego Ironworks, Spacious Cave, Whiteout Cave, Icy Cave, Glacial Cavern",
  "76": "Evolve Geodude/Alolan Geodude/Graveler/Alolan Graveler",
  "87": "Route 226, 230, Fountainspring Cave, Whiteout Cave, Icy Cave, Glacial Cavern",
  "75": "Route 211, 214, 216, 227, Iron Island, Mt. Coronet, Snowpoint Temple, Stark Mountain, Valor Lakefront, Victory Road, Spacious Cave, Rocky Cave, Volcanic Cave, Big Bluff Cavern, Typhlo Cavern",
  "86": "Route 226, 230, Fountainspring Cave, Whiteout Cave, Icy Cave, Glacial Cavern",
  "85": "Evolve Doduo",
  "89": "Evolve Grimer/Alolan Grimer",
  "90": "Route 205, Fuego Ironworks, Valley Windworks, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "79": "Trade/migrate from another game",
  "83": "Route 221, Spacious Cave, Grassland Cave, Fountainspring Cave, Sunlit Cavern",
  "88": "Route 212, Swampy Cave, Dazzling Cave, Stargleam Cavern, Bogsunk Cavern",
  "92": "Route 209, Lost Tower, Old Chateau, Dazzling Cave, Stargleam Cavern",
  "98": "Route 226, Spacious Cave, Dazzling Cave, Stargleam Cavern",
  "94": "Evolve Gastly/Haunter",
  "93": "Turnback Cave",
  "95": "Iron Island, Oreburgh Mine, Snowpoint Temple, Stark Mountain, Victory Road, Rocky Cave, Volcanic Cave, Sandsear Cave, Big Bluff Cavern, Typhlo Cavern",
  "91": "Evolve Shellder",
  "100": "Route 218, Spacious Cave, Dazzling Cave, Stargleam Cavern",
  "97": "Evolve Drowzee",
  "99": "Evolve Krabby",
  "101": "Evolve Voltorb/Hisuian Voltorb",
  "96": "Route 215, Dazzling Cave, Stargleam Cavern",
  "102": "Trade/migrate from another game",
  "103": "Trade/migrate from another game",
  "104": "Route 203, Rocky Cave, Dazzling Cave, Riverbank Cave, Still-Water Cavern, Big Bluff Cavern, Stargleam Cavern",
  "106": "Evolve Tyrogue",
  "108": "Lake Valor, Spacious Cave, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "114": "Swampy Cave, Bogsunk Cavern",
  "109": "Breed Weezing/Galarian Weezing",
  "107": "Evolve Tyrogue",
  "105": "Evolve Cubone",
  "111": "Route 227, Stark Mountain, Spacious Cave, Rocky Cave, Sandsear Cave, Sunlit Cavern, Big Bluff Cavern, Typhlo Cavern",
  "77": "Route 206, 210, 211, 214, 215, Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "116": "Route 226, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "117": "Route 226",
  "112": "Route 227, 228, Stark Mountain, Spacious Cave, Rocky Cave, Sandsear Cave, Big Bluff Cavern",
  "115": "Trade/migrate from another game",
  "118": "Route 203, 204, 209, 212, 214, Lake Acuity, Lake Valor, Lake Verity, Resort Area, Sendoff Spring, Twinleaf Town",
  "110": "Route 227, Stark Mountain, Swampy Cave, Bogsunk Cavern",
  "113": "Route 209, 210",
  "121": "Evolve Staryu",
  "119": "Route 203, 204, 209, 212, 214, Lake Acuity, Lake Valor, Lake Verity, Resort Area, Sendoff Spring, Twinleaf Town",
  "120": "Canalave City, Sunyshore City, Fountainspring Cave, Icy Cave, Riverbank Cave, Still-Water Cavern, Glacial Cavern",
  "125": "Evolve Elekid",
  "128": "Route 209, 210, Spacious Cave, Grassland Cave, Fountainspring Cave, Rocky Cave, Whiteout Cave, Icy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Big Bluff Cavern, Glacial Cavern",
  "133": "Trade/migrate from another game",
  "123": "Route 229, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Big Bluff Cavern",
  "127": "Trade/migrate from another game",
  "130": "Route 203, 204, 205, 208, 209, 210, 212, 213, 214, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, Canalave City, Celestic Town, Eterna City, Fuego Ironworks, Great Marsh, Iron Island, Lake Acuity, Lake Valor, Lake Verity, Mt. Coronet, Oreburgh Gate, Pastoria City, Pokémon League, Ravaged Path, Resort Area, Sendoff Spring, Sunyshore City, Twinleaf Town, Valley Windworks, Victory Road",
  "132": "Route 218, Dazzling Cave, Stargleam Cavern",
  "124": "Evolve Smoochum",
  "126": "Trade/migrate from another game",
  "129": "Route 203, 204, 205, 208, 209, 210, 212, 213, 214, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, Canalave City, Celestic Town, Eterna City, Fuego Ironworks, Great Marsh, Iron Island, Lake Acuity, Lake Valor, Lake Verity, Mt. Coronet, Oreburgh Gate, Pastoria City, Pokémon League, Ravaged Path, Resort Area, Sendoff Spring, Sunyshore City, Twinleaf Town, Valley Windworks, Victory Road",
  "131": "Victory Road",
  "122": "Route 218, 222, Dazzling Cave, Whiteout Cave, Icy Cave, Stargleam Cavern, Glacial Cavern",
  "134": "Trade/migrate from another game",
  "140": "Trade/migrate from another game",
  "138": "Trade/migrate from another game",
  "137": "Trade/migrate from another game",
  "139": "Trade/migrate from another game",
  "146": "Trade/migrate from another game",
  "142": "Trade/migrate from another game",
  "141": "Trade/migrate from another game",
  "147": "Mt. Coronet, Fountainspring Cave",
  "150": "Trade/migrate from another game",
  "135": "Trade/migrate from another game",
  "143": "Evolve Munchlax",
  "136": "Trade/migrate from another game",
  "149": "Evolve Dratini/Dragonair",
  "145": "Trade/migrate from another game",
  "148": "Mt. Coronet",
  "144": "Trade/migrate from another game",
  "151": "Trade/migrate from another game",
  "156": "Evolve Cyndaquil",
  "155": "Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "153": "Evolve Chikorita",
  "160": "Evolve Totodile/Croconaw",
  "152": "Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "157": "Evolve Cyndaquil/Quilava",
  "159": "Evolve Totodile",
  "166": "Route 229, Grassland Cave, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern",
  "22": "Route 225, 226, 227, Stark Mountain",
  "154": "Evolve Chikorita/Bayleef",
  "165": "Breed Ledian",
  "161": "Route 202, Spacious Cave, Rocky Cave, Volcanic Cave, Whiteout Cave, Big Bluff Cavern, Typhlo Cavern",
  "167": "Breed Ariados",
  "163": "Route 210, 211, Great Marsh, Spacious Cave, Grassland Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "162": "Spacious Cave, Rocky Cave, Volcanic Cave, Whiteout Cave, Big Bluff Cavern, Typhlo Cavern",
  "169": "Evolve Zubat/Golbat",
  "168": "Route 229, Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "175": "Route 230, Fountainspring Cave, Dazzling Cave, Stargleam Cavern",
  "176": "Evolve Togepi",
  "164": "Route 210, 211, 216, 217, Acuity Lakefront, Great Marsh, Lake Acuity, Lake Valor, Mt. Coronet, Sendoff Spring",
  "170": "Route 220, Fountainspring Cave, Icy Cave, Glacial Cavern",
  "174": "Trade/migrate from another game",
  "173": "Mt. Coronet",
  "178": "Evolve Natu",
  "180": "Route 222, Grassland Cave, Whiteout Cave, Sunlit Cavern",
  "182": "Evolve Oddish/Gloom",
  "179": "Valley Windworks, Grassland Cave, Whiteout Cave, Sunlit Cavern",
  "38": "Trade/migrate from another game",
  "158": "Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "177": "Route 224, Spacious Cave, Dazzling Cave, Stargleam Cavern",
  "181": "Evolve Mareep/Flaaffy",
  "183": "Great Marsh",
  "39": "Trade/migrate from another game",
  "185": "Trade/migrate from another game",
  "188": "Route 205, Grassland Cave, Sunlit Cavern",
  "189": "Evolve Hoppip/Skiploom",
  "186": "Evolve Poliwag/Poliwhirl",
  "184": "Evolve Marill/Azurill",
  "187": "Route 205, Grassland Cave, Sunlit Cavern",
  "191": "Route 204, Grassland Cave, Sunlit Cavern",
  "194": "Route 212, Great Marsh, Fountainspring Cave, Swampy Cave, Bogsunk Cavern",
  "195": "Route 212, Great Marsh, Fountainspring Cave, Swampy Cave, Bogsunk Cavern",
  "192": "Evolve Sunkern",
  "190": "Spacious Cave",
  "197": "Trade/migrate from another game",
  "202": "Lake Acuity, Lake Valor, Lake Verity, Dazzling Cave, Stargleam Cavern",
  "201": "Solaceon Ruins",
  "200": "Trade/migrate from another game",
  "196": "Trade/migrate from another game",
  "198": "Eterna Forest, Lost Tower, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "203": "Route 214, Valor Lakefront, Dazzling Cave, Stargleam Cavern",
  "199": "Trade/migrate from another game",
  "193": "Trade/migrate from another game",
  "205": "Evolve Pineco",
  "204": "Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "206": "Route 208",
  "207": "Rocky Cave, Swampy Cave, Sunlit Cavern, Big Bluff Cavern, Bogsunk Cavern",
  "210": "Evolve Snubbull",
  "62": "Evolve Poliwag/Poliwhirl",
  "171": "Route 220, Fountainspring Cave, Icy Cave, Glacial Cavern",
  "209": "Route 209, Dazzling Cave, Stargleam Cavern",
  "214": "Trade/migrate from another game",
  "213": "Grassland Cave, Rocky Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Big Bluff Cavern",
  "219": "Stark Mountain, Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "215": "Route 216, 217, Acuity Lakefront, Lake Acuity, Snowpoint Temple, Whiteout Cave, Icy Cave, Glacial Cavern",
  "212": "Evolve Scyther",
  "220": "Route 217, Swampy Cave, Whiteout Cave, Icy Cave, Glacial Cavern, Bogsunk Cavern",
  "223": "Route 213, 222, 223, 224, 230, Pastoria City, Pokémon League, Sunyshore City",
  "216": "Trade/migrate from another game",
  "222": "Route 230, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "224": "Route 213, 222, 223, 224, 230, Pastoria City, Pokémon League, Sunyshore City, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "218": "Stark Mountain, Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "221": "Evolve Swinub",
  "211": "Iron Island, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "226": "Evolve Mantyke",
  "231": "Route 207, Rocky Cave, Big Bluff Cavern",
  "227": "Route 227, Stark Mountain",
  "235": "Route 212",
  "233": "Trade/migrate from another game",
  "234": "Trade/migrate from another game",
  "236": "Route 208, 211, Spacious Cave, Grassland Cave, Whiteout Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "225": "Route 216, Whiteout Cave, Icy Cave, Glacial Cavern",
  "241": "Route 209, 210, Spacious Cave, Grassland Cave, Sunlit Cavern",
  "238": "Lake Acuity, Dazzling Cave, Icy Cave, Stargleam Cavern, Glacial Cavern",
  "239": "Dazzling Cave, Whiteout Cave, Stargleam Cavern, Glacial Cavern",
  "232": "Evolve Phanpy",
  "240": "Trade/migrate from another game",
  "229": "Spacious Cave, Volcanic Cave, Dazzling Cave, Sandsear Cave, Stargleam Cavern, Typhlo Cavern",
  "237": "Evolve Tyrogue",
  "250": "Trade/migrate from another game",
  "246": "Route 207, Rocky Cave, Big Bluff Cavern",
  "230": "Evolve Horsea/Seadra",
  "252": "Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "253": "Evolve Treecko",
  "245": "Trade/migrate from another game",
  "243": "Trade/migrate from another game",
  "242": "Evolve Chansey/Happiny",
  "249": "Trade/migrate from another game",
  "251": "Trade/migrate from another game",
  "244": "Trade/migrate from another game",
  "256": "Evolve Torchic",
  "248": "Evolve Larvitar/Pupitar",
  "247": "Rocky Cave, Big Bluff Cavern",
  "208": "Iron Island, Snowpoint Temple, Victory Road",
  "255": "Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "259": "Evolve Mudkip",
  "217": "Trade/migrate from another game",
  "254": "Evolve Treecko/Grovyle",
  "260": "Evolve Mudkip/Marshtomp",
  "257": "Evolve Torchic/Combusken",
  "264": "Evolve Zigzagoon/Galarian Zigzagoon",
  "258": "Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "262": "Route 214, 215, Spacious Cave, Dazzling Cave, Icy Cave, Stargleam Cavern, Glacial Cavern",
  "266": "Eterna Forest, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "261": "Spacious Cave, Dazzling Cave, Icy Cave, Stargleam Cavern, Glacial Cavern",
  "263": "Route 202, Spacious Cave, Rocky Cave, Big Bluff Cavern",
  "228": "Breed Houndoom",
  "272": "Trade/migrate from another game",
  "265": "Eterna Forest, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "275": "Evolve Seedot/Nuzleaf",
  "268": "Evolve Wurmple",
  "271": "Trade/migrate from another game",
  "269": "Evolve Wurmple/Silcoon/Cascoon",
  "267": "Route 224, 230, Eterna Forest",
  "270": "Trade/migrate from another game",
  "276": "Breed Swellow",
  "274": "Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "279": "Route 205, 213, 218, 219, 220, 221, 222, 223, 224, 226, 229, 230, Canalave City, Fuego Ironworks, Iron Island, Pastoria City, Pokémon League, Sunyshore City, Valley Windworks, Spacious Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "282": "Evolve Ralts/Kirlia",
  "277": "Route 213",
  "273": "Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "278": "Route 205, 213, 218, 219, 220, 221, 222, 229, Canalave City, Fuego Ironworks, Iron Island, Pastoria City, Valley Windworks, Spacious Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "280": "Route 203, 204, Fountainspring Cave, Dazzling Cave, Stargleam Cavern",
  "285": "Trade/migrate from another game",
  "290": "Eterna Forest, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "284": "Evolve Surskit",
  "286": "Trade/migrate from another game",
  "289": "Evolve Slakoth/Vigoroth",
  "283": "Lake Verity, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "288": "Evolve Slakoth",
  "292": "Evolve Nincada",
  "281": "Route 203, 204, Dazzling Cave, Stargleam Cavern",
  "299": "Route 206",
  "293": "Breed Loudred/Exploud",
  "291": "Evolve Nincada",
  "301": "Evolve Skitty",
  "297": "Evolve Makuhita",
  "294": "Mt. Coronet",
  "295": "Evolve Whismur/Loudred",
  "298": "Great Marsh",
  "296": "Route 225",
  "302": "Trade/migrate from another game",
  "307": "Route 208, 210, 211, 216, 217, Acuity Lakefront, Mt. Coronet, Dazzling Cave, Whiteout Cave, Stargleam Cavern",
  "300": "Route 222, Spacious Cave",
  "305": "Rocky Cave, Whiteout Cave, Icy Cave, Big Bluff Cavern, Glacial Cavern",
  "303": "Dazzling Cave, Stargleam Cavern",
  "311": "Trade/migrate from another game",
  "316": "Trade/migrate from another game",
  "314": "Route 229, Grassland Cave, Dazzling Cave, Sunlit Cavern, Stargleam Cavern",
  "315": "Route 212, 221, 224, 225, 229, Trophy Garden, Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "287": "Eterna Forest",
  "313": "Route 229, Grassland Cave, Dazzling Cave, Sunlit Cavern, Stargleam Cavern",
  "317": "Trade/migrate from another game",
  "306": "Evolve Aron/Lairon",
  "309": "Valley Windworks",
  "319": "Route 213, 222",
  "312": "Trade/migrate from another game",
  "304": "Fuego Ironworks, Rocky Cave, Whiteout Cave, Icy Cave, Big Bluff Cavern, Glacial Cavern",
  "310": "Evolve Electrike",
  "318": "Great Marsh, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "320": "Route 223, 230",
  "322": "Route 227, Stark Mountain, Rocky Cave, Volcanic Cave, Sandsear Cave, Big Bluff Cavern, Typhlo Cavern",
  "323": "Route 227, Stark Mountain, Rocky Cave, Volcanic Cave, Sandsear Cave, Big Bluff Cavern, Typhlo Cavern",
  "324": "Route 227, Stark Mountain, Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "321": "Route 223, 230",
  "330": "Evolve Trapinch/Vibrava",
  "327": "Route 227",
  "337": "Trade/migrate from another game",
  "326": "Evolve Spoink",
  "333": "Route 211, Spacious Cave, Fountainspring Cave, Whiteout Cave, Icy Cave, Glacial Cavern",
  "334": "Evolve Swablu",
  "336": "Trade/migrate from another game",
  "325": "Route 214",
  "331": "Route 228, Grassland Cave, Rocky Cave, Swampy Cave, Sunlit Cavern, Big Bluff Cavern, Bogsunk Cavern",
  "329": "Route 228, Grassland Cave, Rocky Cave, Sunlit Cavern, Big Bluff Cavern",
  "335": "Grassland Cave, Swampy Cave, Dazzling Cave, Sunlit Cavern, Stargleam Cavern, Bogsunk Cavern",
  "338": "Dazzling Cave, Riverbank Cave, Still-Water Cavern, Stargleam Cavern",
  "328": "Route 228, Rocky Cave, Sandsear Cave, Big Bluff Cavern",
  "341": "Celestic Town, Spacious Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "172": "Trophy Garden",
  "345": "Trade/migrate from another game",
  "346": "Trade/migrate from another game",
  "332": "Route 228, Grassland Cave, Rocky Cave, Swampy Cave, Sunlit Cavern, Big Bluff Cavern, Bogsunk Cavern",
  "342": "Celestic Town, Spacious Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "344": "Evolve Baltoy",
  "340": "Route 205, 208, 210, 212, 227, 228, Celestic Town, Eterna City, Great Marsh, Mt. Coronet, Oreburgh Gate, Ravaged Path, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "349": "Trade/migrate from another game",
  "343": "Route 206, Rocky Cave, Dazzling Cave, Big Bluff Cavern, Stargleam Cavern",
  "350": "Trade/migrate from another game",
  "353": "Breed Banette",
  "347": "Trade/migrate from another game",
  "351": "Trade/migrate from another game",
  "348": "Trade/migrate from another game",
  "356": "Route 224, Dazzling Cave, Stargleam Cavern",
  "352": "Route 210, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "360": "Breed Wobbuffet",
  "359": "Route 213, Spacious Cave, Grassland Cave, Dazzling Cave, Sunlit Cavern, Big Bluff Cavern, Stargleam Cavern",
  "358": "Mt. Coronet, Sendoff Spring",
  "308": "Route 217, Acuity Lakefront, Mt. Coronet, Victory Road",
  "355": "Route 224, Dazzling Cave, Stargleam Cavern",
  "357": "Grassland Cave, Swampy Cave, Sunlit Cavern, Bogsunk Cavern",
  "365": "Whiteout Cave, Icy Cave, Glacial Cavern",
  "354": "Route 225, 226, 227, Stark Mountain, Dazzling Cave, Stargleam Cavern",
  "363": "Breed Sealeo/Walrein",
  "362": "Whiteout Cave, Icy Cave, Glacial Cavern",
  "361": "Route 216, 217, Acuity Lakefront, Whiteout Cave, Icy Cave, Glacial Cavern",
  "364": "Evolve Spheal",
  "366": "Route 219, 221, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "369": "Route 226",
  "368": "Evolve Clamperl",
  "374": "Route 228, Rocky Cave, Whiteout Cave, Icy Cave, Big Bluff Cavern, Glacial Cavern",
  "376": "Evolve Beldum/Metang",
  "371": "Trade/migrate from another game",
  "375": "Evolve Beldum",
  "372": "Trade/migrate from another game",
  "367": "Evolve Clamperl",
  "379": "Trade/migrate from another game",
  "373": "Trade/migrate from another game",
  "378": "Trade/migrate from another game",
  "377": "Trade/migrate from another game",
  "381": "Trade/migrate from another game",
  "380": "Trade/migrate from another game",
  "339": "Route 205, 208, 210, 212, 227, 228, Celestic Town, Eterna City, Great Marsh, Mt. Coronet, Oreburgh Gate, Ravaged Path, Fountainspring Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "382": "Trade/migrate from another game",
  "383": "Trade/migrate from another game",
  "393": "Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "385": "Trade/migrate from another game",
  "397": "Route 209, 212, Lake Valor, Sendoff Spring, Trophy Garden, Valor Lakefront",
  "389": "Evolve Turtwig/Grotle",
  "387": "Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "395": "Evolve Piplup/Prinplup",
  "391": "Evolve Chimchar",
  "390": "Volcanic Cave, Sandsear Cave, Typhlo Cavern",
  "396": "Route 201, 202, 203, 204, 209, 212, Great Marsh, Lake Verity",
  "388": "Evolve Turtwig",
  "394": "Evolve Piplup",
  "392": "Evolve Chimchar/Monferno",
  "384": "Trade/migrate from another game",
  "399": "Route 201, 202, 203, 204, 205, 208, 211, Great Marsh, Lake Verity, Valley Windworks, Spacious Cave, Grassland Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "400": "Route 208, 209, 210, 212, Great Marsh, Lake Acuity, Lake Valor, Sendoff Spring, Valor Lakefront, Spacious Cave, Grassland Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "405": "Evolve Shinx/Luxio",
  "401": "Route 202, 203, 204, 206, 207, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "406": "Route 204, 212, Eterna Forest, Great Marsh, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "386": "Trade/migrate from another game",
  "402": "Route 206, 210, 212, 214, 215, Trophy Garden, Valor Lakefront",
  "404": "Fuego Ironworks, Spacious Cave, Grassland Cave, Whiteout Cave, Sunlit Cavern",
  "414": "Trade/migrate from another game",
  "415": "Grassland Cave, Sunlit Cavern",
  "398": "Evolve Starly/Staravia",
  "410": "Trade/migrate from another game",
  "413": "Trade/migrate from another game",
  "417": "Route 205, Fuego Ironworks, Valley Windworks, Spacious Cave, Whiteout Cave",
  "403": "Route 202, 203, 204, Fuego Ironworks, Spacious Cave, Grassland Cave, Whiteout Cave, Sunlit Cavern",
  "409": "Trade/migrate from another game",
  "416": "Evolve Combee",
  "370": "Route 224, Pokémon League",
  "411": "Trade/migrate from another game",
  "408": "Trade/migrate from another game",
  "419": "Route 213, 218, 221, 222, 224, 230, Fuego Ironworks, Victory Road",
  "427": "Eterna Forest, Spacious Cave, Grassland Cave, Whiteout Cave, Icy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Glacial Cavern",
  "420": "Grassland Cave, Sunlit Cavern",
  "421": "Evolve Cherubi",
  "412": "Trade/migrate from another game",
  "418": "Route 205, 213, 224, Valley Windworks, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "422": "Route 205, 213, 218, 221, 224, Fuego Ironworks, Valley Windworks, Fountainspring Cave",
  "424": "Evolve Aipom",
  "429": "Trade/migrate from another game",
  "435": "Route 221, 225, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "426": "Trade/migrate from another game",
  "433": "Route 211, Lake Acuity, Lake Valor, Mt. Coronet, Spacious Cave, Dazzling Cave, Stargleam Cavern",
  "436": "Route 206, Mt. Coronet, Turnback Cave, Wayward Cave, Rocky Cave, Dazzling Cave, Icy Cave, Big Bluff Cavern, Stargleam Cavern, Glacial Cavern",
  "423": "Route 218, 221, 222, 224, 230, Fuego Ironworks, Fountainspring Cave",
  "432": "Trade/migrate from another game",
  "434": "Route 206, 214, 221, Spacious Cave, Grassland Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "430": "Evolve Murkrow",
  "428": "Evolve Buneary",
  "437": "Mt. Coronet, Turnback Cave",
  "443": "Wayward Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "438": "Trade/migrate from another game",
  "442": "Trade/migrate from another game",
  "439": "Route 209, 210",
  "440": "Breed Chansey/Blissey",
  "444": "Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "446": "Spacious Cave, Grassland Cave, Whiteout Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern",
  "445": "Evolve Gible/Gabite",
  "431": "Trade/migrate from another game",
  "447": "Trade/migrate from another game",
  "451": "Rocky Cave, Volcanic Cave, Swampy Cave, Sandsear Cave, Big Bluff Cavern, Bogsunk Cavern, Typhlo Cavern",
  "452": "Evolve Skorupi",
  "425": "Trade/migrate from another game",
  "449": "Ruin Maniac Tunnel, Rocky Cave, Sandsear Cave, Big Bluff Cavern",
  "450": "Route 228",
  "453": "Swampy Cave, Riverbank Cave, Still-Water Cavern, Bogsunk Cavern",
  "448": "Trade/migrate from another game",
  "407": "Evolve Roselia/Budew",
  "458": "Route 223, Sunyshore City, Spacious Cave, Fountainspring Cave, Riverbank Cave, Still-Water Cavern",
  "465": "Swampy Cave, Bogsunk Cavern",
  "454": "Evolve Croagunk",
  "468": "Evolve Togepi/Togetic",
  "461": "Evolve Sneasel/Hisuian Sneasel",
  "456": "Route 205, 218, 219, 220, 221, Canalave City, Fuego Ironworks, Iron Island, Valley Windworks",
  "459": "Route 216, 217, Acuity Lakefront, Mt. Coronet, Whiteout Cave, Icy Cave, Glacial Cavern",
  "466": "Evolve Electabuzz/Elekid",
  "463": "Evolve Lickitung",
  "467": "Trade/migrate from another game",
  "471": "Trade/migrate from another game",
  "462": "Evolve Magnemite/Magneton",
  "464": "Evolve Rhyhorn/Rhydon",
  "470": "Trade/migrate from another game",
  "457": "Route 205, 218, 219, 220, 221, Canalave City, Fuego Ironworks, Iron Island, Valley Windworks",
  "469": "Trade/migrate from another game",
  "473": "Evolve Swinub/Piloswine",
  "460": "Mt. Coronet",
  "472": "Evolve Gligar",
  "455": "Trade/migrate from another game",
  "474": "Trade/migrate from another game",
  "477": "Evolve Duskull/Dusclops",
  "481": "Trade/migrate from another game",
  "475": "Evolve Ralts/Kirlia",
  "478": "Evolve Snorunt",
  "487": "Trade/migrate from another game",
  "480": "Trade/migrate from another game",
  "489": "Trade/migrate from another game",
  "488": "Trade/migrate from another game",
  "492": "Trade/migrate from another game",
  "493": "Trade/migrate from another game",
  "483": "Trade/migrate from another game",
  "486": "Trade/migrate from another game",
  "484": "Trade/migrate from another game",
  "482": "Trade/migrate from another game",
  "485": "Trade/migrate from another game",
  "490": "Trade/migrate from another game",
  "479": "Trade/migrate from another game",
  "476": "Evolve Nosepass",
  "491": "Trade/migrate from another game",
  "441": "Route 222, 224"
};
